### PR TITLE
fix(push publish): parse --message as a full Ably message shape

### LINKED ISSUE #347: Push publish message flag
In https://github.com/ably/ably-cli/pull/310 `--message` flag can be a string, or a JSON, but internally it applies to message's `data` field, which makes it impossible to set message's name. I wonder why it was decided that way. Because of it you get the first "undefined" on this [screenshot](https://raw.githubusercontent.com/ably/docs/966396e708b6a41e3323ff199c09c89470ed5ddd/src/images/content/screenshots/getting-started/react-native-push-getting-started-guide.png). FYI @umair-ably (please comment here before implementing to avoid merging conflicts).

### PR DESCRIPTION
**Pull request by umair-ably**
## Summary

- `ably push publish --message` now parses JSON input as a full Ably message (`name`, `data`, `extras`) instead of always stuffing the parsed value into `data`. This matches the semantics of `ably channels publish` and makes it possible to set the realtime message's `name`.
- Reuses the existing `prepareMessageFromInput()` helper in `src/utils/message.ts` — no new utility.
- The CLI-built push payload is still attached as `extras.push` on the published message; any user-supplied `extras` keys are merged alongside it.
- If `--message` already contains `extras.push`, the command fails with a clear error (the CLI owns that field via `--title` / `--body` / `--payload` / etc.).
- JSON output (`--json`) now includes `messageName` and `messageData` when present, making the result self-describing (replaces the previous `messageData: true` boolean sentinel).

Follow-up to #310 (addresses the reviewer comment that `--message` couldn't set the message name).

### Behaviour change ⚠️

Moving to `prepareMessageFromInput` means any JSON object that already contains top-level `name`, `data`, or `extras` keys is now treated as a full Ably message shape. This is the point of the change, but two cases are worth calling out explicitly:

| `--message` input | Before | After |
|---|---|---|
| `'hello'` (plain string) | `data: "hello"` | `data: "hello"` — unchanged |
| `'{"key":"val"}'` (object, no reserved keys) | `data: { key: "val" }` | `data: { key: "val" }` — unchanged |
| `'{"name":"alert","data":"hi"}'` | `data: { name: "alert", data: "hi" }` | **`name: "alert"`, `data: "hi"`** — new capability |
| `'{"data":"hi"}'` | `data: { data: "hi" }` | **`data: "hi"`** — inner value unwrapped |
| `'{"extras":{"headers":{...}}}'` | `data: { extras: {...} }` | **`extras: { headers: {...}, push: ... }`** — merged |
| `'{"extras":{"push":{...}}}'` | `data: { extras: { push: {...} } }` | **Error** — CLI owns `extras.push` |

Callers who relied on the previous (arguably incorrect) behaviour where `{"data":"x"}` was stored as `data: { data: "x" }` will see the inner value unwrapped instead. The new shape matches `channels publish` and how a plain Ably realtime subscriber expects messages.

## Test plan

- [x] `pnpm prepare` (build + manifest) succeeds
- [x] `pnpm exec eslint src/commands/push/publish.ts test/unit/commands/push/publish.test.ts` — 0 errors
- [x] `pnpm test test/unit/commands/push/publish.test.ts` — 32/32 pass, including:
  - full message object sets `name` and `data`
  - bare object without reserved keys stays wrapped as `data`
  - top-level `data` key is unwrapped (behaviour-change assertion)
  - user `extras` merged with `push`
  - `extras.push` collision fails with clear error, publish is not called
  - JSON output surfaces `messageName` + `messageData`
- [x] `pnpm test:unit` — full suite green
- [ ] Manual smoke against a real Ably app (recommended before merge):
  - `ably push publish --channel demo --title Hi --message '{"name":"alert","data":"hi"}' --force` — verify a realtime subscriber sees `name === "alert"` and `data === "hi"`.
  - `ably push publish --channel demo --title Hi --message '{"extras":{"push":{"notification":{"title":"x"}}}}' --force` — verify the collision error and non-zero exit.

### CODE REVIEW

File: src/commands/push/publish.ts [hunk 1]
```diff
@@ -25,6 +26,7 @@ export default class PushPublish extends AblyBaseCommand {
     "<%= config.bin %> <%= command.id %> --channel my-channel --payload ./notification.json",
     "<%= config.bin %> <%= command.id %> --channel my-channel --title Hello --body World --message 'Hello from push'",
     '<%= config.bin %> <%= command.id %> --channel my-channel --title Hello --body World --message \'{"event":"push","text":"Hello"}\'',
+    '<%= config.bin %> <%= command.id %> --channel my-channel --title Hello --body World --message \'{"name":"alert","data":"Server down"}\'',
```
Comment (maratal) [inline src/commands/push/publish.ts]: This is not very positive example =)

File: src/commands/push/publish.ts [hunk 2]
```diff
@@ -49,7 +51,7 @@ export default class PushPublish extends AblyBaseCommand {
     }),
     message: Flags.string({
       description:
-        "Realtime message data to include alongside the push notification (only applies when publishing via --channel)",
+        'Realtime message to include alongside the push notification. Accepts plain text, JSON data, or a full message object ({"name":...,"data":...,"extras":...}). Only applies when publishing via --channel.',
```
Comment (maratal) [inline src/commands/push/publish.ts]: Code below doesn't implement this - if full message object fields are not found, than `publishMessage` object remains empty, i.e. if I'm passing "{"foo": "bar"}" as `--message` it will not be sent.

**Review by maratal — COMMENTED** [review]
A suggestion.

File: src/commands/push/publish.ts (hunk 1 above)
Comment (umair-ably) [reply src/commands/push/publish.ts]: [295a823](https://github.com/ably/ably-cli/pull/352/commits/295a82314ca7b76e1412e70685ed9cab0278f8b1)

**Review by maratal — APPROVED** [review]
LGTM
